# Forked from https://github.com/pubref/rules_protobuf
dist: trusty
language: java
jdk:
  - openjdk8
  - oraclejdk9

os: linux

cache:
  directories:
    - $HOME/bazel/install
    - $HOME/bazel/outbase

before_install:
  - BAZEL_VERSION=0.10.0
  - OS=linux
  - ARCH=x86_64
  - GH_BASE="https://github.com/bazelbuild/bazel/releases/download/$BAZEL_VERSION"
  - GH_ARTIFACT="bazel-$BAZEL_VERSION-installer-$OS-$ARCH.sh"
  - URL="$GH_BASE/$GH_ARTIFACT"
  - echo $URL
  - mkdir -p ${HOME}/bazel/install
  - cd ${HOME}/bazel/install
  - wget -c -O install_$BAZEL_VERSION.sh $URL
  - chmod +x install_$BAZEL_VERSION.sh
  - ./install_$BAZEL_VERSION.sh --user
  - cd ${TRAVIS_BUILD_DIR}

script:
  - |
    bazel \
      --output_base=$HOME/bazel/outbase \
      --batch \
      --host_jvm_args=-Xmx500m \
      --host_jvm_args=-Xms500m \
      test \
      --verbose_failures \
      --test_output=errors \
      --test_strategy=standalone \
      --spawn_strategy=standalone \
      --genrule_strategy=standalone \
      --local_resources=400,2,1.0 \
      --worker_verbose \
      --strategy=Javac=worker \
      --strategy=Closure=worker \
      //src/test/... \
      $FLAGS

notifications:
  email: false
